package jy.zhongye.service.account;

import jy.zhongye.entity.account.Permission;
import jy.zhongye.entity.account.Role;
import jy.zhongye.entity.account.User;
import jy.zhongye.entity.common.Result;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
public interface AccountService {

//    User
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<User> selectAllUser();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    List<Role> selectAllRole();


//    User-Role
    /***
     * @method getPassword
     * @description
     * @author
     * @date
     * @param        username
     * @return
     */
    String getPassword(String username);

    /***
     * @method listRoles
     * @description
     * @author
     * @date
     * @param        user
     * @return
     */
    List<Role> listRoles(User user);

    /***
     * @method listPermissions
     * @description
     * @author
     * @date
     * @param        user
     * @return
     */
    List<Permission> listPermissions(User user);

    /***
     * @method listPermissionByRole
     * @description
     * @author
     * @date
     * @param        role
     * @return
     */
    List<Permission> listPermissionsByRole(Role role);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated
     */
    List<Permission> selectAllPermission();


    /**
     * @Description:
     * @Param: [username, password, roles]
     * @return: int
     * @Author: Mr.Xuyu
     * @Date: 2019-01-10
     */
    Result addUser(String username, String password, List<Role> roles);

    /**
     * @Description:
     * @Param: [username]
     * @return: java.lang.Long
     * @Author: Mr.Xuyu
     * @Date: 2019-01-10
     */
    User getUserByUsername(String username);

    /**
     * @Description:
     * @Param: [roleName]
     * @return: java.lang.Long
     * @Author: Mr.Xuyu
     * @Date: 2019-01-10
     */
    Role getRoleByRoleName(String roleName);

    /**
     * @Description:
     * @Param: [permissionName]
     * @return: java.lang.Long
     * @Author: Mr.Xuyu
     * @Date: 2019-01-10
     */
    Permission getPermissionByPermissionName(String permissionName);

    /**
     * @Description:
     * @Param: [roleName, roleDesc, permissions]
     * @return: int
     * @Author: Mr.Xuyu
     * @Date: 2019-01-10
     */
    Result addRole(String roleName,String roleDesc,List<Permission> permissions);

    /**
     * @Description:添加权限
     * @Param: [permissionName, permissionDesc]
     * @return: jy.zhongye.entity.common.Result
     * @Author: Mr.Xuyu
     * @Date: 2019-01-24
     */
    Result addPermission(String permissionName, String permissionDesc);

    /**
     * @Description:给一个用户更新重置角色
     * @Param: [user, roles]
     * @return: jy.zhongye.entity.common.Result
     * @Author: Mr.Xuyu
     * @Date: 2019-01-24
     */
    public Result userUpdateRoles(User user, List<Role> roles);

    /**
     * @Description:给一个角色更新重置权限
     * @Param: [user, roles]
     * @return: jy.zhongye.entity.common.Result
     * @Author: Mr.Xuyu
     * @Date: 2019-01-24
     */
    public Result roleUpdatePerminssions(Role role, List<Permission> permissions);
}
